backend: 
  name: github
  branch: master
  repo: rpaspardelli/blog-md

media_folder: static/img
public_folder: /img

collections:
  - name:  author 
    label:  Autores 
    folder: src/authors
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields: 
      - {label:  Nome , name:  title , widget:  String }
      - {label:  Avatar , name:  avatar , widget:  image }
      - {label:  Bio , name:  body , widget:  markdown }

  - name: blog
    label: Blog Posts
    folder: src/content
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"
    fields: 
      - { label: Titulo, name: 'title', widget: string}
      - { label: Descrição, name: description, widget: string}
      - { label: Banner, name: banner, widget: image}